use_frameworks!

platform :ios, '11.0'

target 'MoEPluginBaseExample' do
  pod 'MoEngagePluginBase', :path => '../'
  pod 'MoEngagePluginGeofence', :path => '../'
  pod 'MoEngagePluginInbox', :path => '../'
  pod 'MoEngagePluginCards', :path => '../', :testspecs => ['UnitTests']

  target 'MoEPluginBaseExampleTests' do
    inherit! :search_paths
  end
end
