use_frameworks!

platform :ios, '11.0'

target 'MoEPluginBaseExample' do
  pod 'MoEngageSegmentPluginBase', :path => '../'
  target 'MoEPluginBaseExampleTests' do
    inherit! :search_paths
  end
end
