name: Create stable release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create release
    runs-on: macos-latest
    steps:
    - name: Checkout scripts
      uses: actions/checkout@v4
      with:
        path: scripts
        repository: moengage/sdk-automation-scripts
        token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
        fetch-depth: 0
        fetch-tags: true

    - name: Setup dev environment
      uses: ./scripts/actions/ios-action-setup
      env:
        SDK_BOT_ACCESS_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: source
        token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
        fetch-depth: 0
        fetch-tags: true

    - name: Setup dev environment
      uses: ./scripts/actions/action-git-development-to-master
      with:
        dir: source

    - name: Create release
      uses: ./scripts/actions/ios-sdk-client-release
      with:
        dir: source
      env:
        GITHUB_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
